// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppSundials.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// wrap_cvodes
NumericVector wrap_cvodes(NumericVector times, NumericVector states_, NumericVector parameters_, List forcings_data_, List settings, SEXP model_, SEXP jacobian_);
static SEXP _RcppSundials_wrap_cvodes_try(SEXP timesSEXP, SEXP states_SEXP, SEXP parameters_SEXP, SEXP forcings_data_SEXP, SEXP settingsSEXP, SEXP model_SEXP, SEXP jacobian_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type states_(states_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parameters_(parameters_SEXP);
    Rcpp::traits::input_parameter< List >::type forcings_data_(forcings_data_SEXP);
    Rcpp::traits::input_parameter< List >::type settings(settingsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type model_(model_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type jacobian_(jacobian_SEXP);
    rcpp_result_gen = Rcpp::wrap(wrap_cvodes(times, states_, parameters_, forcings_data_, settings, model_, jacobian_));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _RcppSundials_wrap_cvodes(SEXP timesSEXP, SEXP states_SEXP, SEXP parameters_SEXP, SEXP forcings_data_SEXP, SEXP settingsSEXP, SEXP model_SEXP, SEXP jacobian_SEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_RcppSundials_wrap_cvodes_try(timesSEXP, states_SEXP, parameters_SEXP, forcings_data_SEXP, settingsSEXP, model_SEXP, jacobian_SEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cvode_calc_derivs
List cvode_calc_derivs(SEXP model_, NumericVector t, NumericVector states, NumericVector parameters, List forcings_data_);
static SEXP _RcppSundials_cvode_calc_derivs_try(SEXP model_SEXP, SEXP tSEXP, SEXP statesSEXP, SEXP parametersSEXP, SEXP forcings_data_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_(model_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type states(statesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< List >::type forcings_data_(forcings_data_SEXP);
    rcpp_result_gen = Rcpp::wrap(cvode_calc_derivs(model_, t, states, parameters, forcings_data_));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _RcppSundials_cvode_calc_derivs(SEXP model_SEXP, SEXP tSEXP, SEXP statesSEXP, SEXP parametersSEXP, SEXP forcings_data_SEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_RcppSundials_cvode_calc_derivs_try(model_SEXP, tSEXP, statesSEXP, parametersSEXP, forcings_data_SEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// cvode_calc_jac
NumericMatrix cvode_calc_jac(SEXP jacobian_, NumericVector t, NumericVector states, NumericVector parameters, List forcings_data_);
static SEXP _RcppSundials_cvode_calc_jac_try(SEXP jacobian_SEXP, SEXP tSEXP, SEXP statesSEXP, SEXP parametersSEXP, SEXP forcings_data_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type jacobian_(jacobian_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type states(statesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< List >::type forcings_data_(forcings_data_SEXP);
    rcpp_result_gen = Rcpp::wrap(cvode_calc_jac(jacobian_, t, states, parameters, forcings_data_));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _RcppSundials_cvode_calc_jac(SEXP jacobian_SEXP, SEXP tSEXP, SEXP statesSEXP, SEXP parametersSEXP, SEXP forcings_data_SEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_RcppSundials_cvode_calc_jac_try(jacobian_SEXP, tSEXP, statesSEXP, parametersSEXP, forcings_data_SEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// idas_Cpp_stl
NumericMatrix idas_Cpp_stl(NumericVector times, NumericVector states_, NumericVector derivatives_, NumericVector parameters_, List forcings_data_, List settings, SEXP model_, SEXP jacobian_);
RcppExport SEXP _RcppSundials_idas_Cpp_stl(SEXP timesSEXP, SEXP states_SEXP, SEXP derivatives_SEXP, SEXP parameters_SEXP, SEXP forcings_data_SEXP, SEXP settingsSEXP, SEXP model_SEXP, SEXP jacobian_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type states_(states_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type derivatives_(derivatives_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parameters_(parameters_SEXP);
    Rcpp::traits::input_parameter< List >::type forcings_data_(forcings_data_SEXP);
    Rcpp::traits::input_parameter< List >::type settings(settingsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type model_(model_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type jacobian_(jacobian_SEXP);
    rcpp_result_gen = Rcpp::wrap(idas_Cpp_stl(times, states_, derivatives_, parameters_, forcings_data_, settings, model_, jacobian_));
    return rcpp_result_gen;
END_RCPP
}
// idas_calc_res
List idas_calc_res(SEXP model_, NumericVector t, NumericVector states, NumericVector derivatives, NumericVector parameters, List forcings_data_);
RcppExport SEXP _RcppSundials_idas_calc_res(SEXP model_SEXP, SEXP tSEXP, SEXP statesSEXP, SEXP derivativesSEXP, SEXP parametersSEXP, SEXP forcings_data_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_(model_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type states(statesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type derivatives(derivativesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< List >::type forcings_data_(forcings_data_SEXP);
    rcpp_result_gen = Rcpp::wrap(idas_calc_res(model_, t, states, derivatives, parameters, forcings_data_));
    return rcpp_result_gen;
END_RCPP
}
// idas_calc_jac
NumericMatrix idas_calc_jac(SEXP jacobian_, NumericVector t, NumericVector states, NumericVector parameters, List forcings_data_);
RcppExport SEXP _RcppSundials_idas_calc_jac(SEXP jacobian_SEXP, SEXP tSEXP, SEXP statesSEXP, SEXP parametersSEXP, SEXP forcings_data_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type jacobian_(jacobian_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type states(statesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< List >::type forcings_data_(forcings_data_SEXP);
    rcpp_result_gen = Rcpp::wrap(idas_calc_jac(jacobian_, t, states, parameters, forcings_data_));
    return rcpp_result_gen;
END_RCPP
}

// validate (ensure exported C++ functions exist before calling them)
static int _RcppSundials_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("NumericVector(*wrap_cvodes)(NumericVector,NumericVector,NumericVector,List,List,SEXP,SEXP)");
        signatures.insert("List(*cvode_calc_derivs)(SEXP,NumericVector,NumericVector,NumericVector,List)");
        signatures.insert("NumericMatrix(*cvode_calc_jac)(SEXP,NumericVector,NumericVector,NumericVector,List)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _RcppSundials_RcppExport_registerCCallable() { 
    R_RegisterCCallable("RcppSundials", "_RcppSundials_wrap_cvodes", (DL_FUNC)_RcppSundials_wrap_cvodes_try);
    R_RegisterCCallable("RcppSundials", "_RcppSundials_cvode_calc_derivs", (DL_FUNC)_RcppSundials_cvode_calc_derivs_try);
    R_RegisterCCallable("RcppSundials", "_RcppSundials_cvode_calc_jac", (DL_FUNC)_RcppSundials_cvode_calc_jac_try);
    R_RegisterCCallable("RcppSundials", "_RcppSundials_RcppExport_validate", (DL_FUNC)_RcppSundials_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppSundials_wrap_cvodes", (DL_FUNC) &_RcppSundials_wrap_cvodes, 7},
    {"_RcppSundials_cvode_calc_derivs", (DL_FUNC) &_RcppSundials_cvode_calc_derivs, 5},
    {"_RcppSundials_cvode_calc_jac", (DL_FUNC) &_RcppSundials_cvode_calc_jac, 5},
    {"_RcppSundials_idas_Cpp_stl", (DL_FUNC) &_RcppSundials_idas_Cpp_stl, 8},
    {"_RcppSundials_idas_calc_res", (DL_FUNC) &_RcppSundials_idas_calc_res, 6},
    {"_RcppSundials_idas_calc_jac", (DL_FUNC) &_RcppSundials_idas_calc_jac, 5},
    {"_RcppSundials_RcppExport_registerCCallable", (DL_FUNC) &_RcppSundials_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppSundials(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
